import type { DashboardSnapshot } from "./domain";

export const demoDashboardSnapshot: DashboardSnapshot = {
  overview: {
    jobsFound: 148,
    aboveThreshold: 32,
    queued: 14,
    prepared: 9,
    autoSubmitted: 11,
    submittedTotal: 11,
    needsUserAction: 3,
    dailyTargetVolume: 15,
    preparedInLast24Hours: 12,
    remainingDailyCapacity: 3,
  },
  applications: [
    {
      id: "app_1",
      company: "Vercel",
      role: "Software Engineer, Integrations",
      source: "Ashby",
      location: "Remote within United States",
      fitScore: 91,
      status: "auto_submitted",
      blockingReason: null,
      manualActionType: null,
      jobUrl: "https://jobs.ashbyhq.com/vercel/software-engineer-integrations",
      applyUrl: "https://jobs.ashbyhq.com/vercel/software-engineer-integrations/apply",
      lastAutomationUrl: "https://jobs.ashbyhq.com/vercel/software-engineer-integrations/apply",
      preparedAt: "2026-04-21T09:06:00.000Z",
      submittedAt: "2026-04-21T09:15:00.000Z",
      needsUserActionAt: null,
      updatedAt: "2026-04-21T09:15:00.000Z",
      generatedAnswersCount: 3,
    },
    {
      id: "app_2",
      company: "Figma",
      role: "Backend Engineer",
      source: "Greenhouse",
      location: "San Francisco, CA",
      fitScore: 88,
      status: "prepared",
      blockingReason: null,
      manualActionType: null,
      jobUrl: "https://boards.greenhouse.io/figma/jobs/123456",
      applyUrl: "https://boards.greenhouse.io/figma/apply/123456",
      lastAutomationUrl: null,
      preparedAt: "2026-04-21T08:48:00.000Z",
      submittedAt: null,
      needsUserActionAt: null,
      updatedAt: "2026-04-21T08:48:00.000Z",
      generatedAnswersCount: 2,
    },
    {
      id: "app_3",
      company: "Stripe",
      role: "Software Engineer, New Grad",
      source: "Company Site",
      location: "Seattle, WA",
      fitScore: 84,
      status: "needs_user_action",
      blockingReason: "Email verification interrupted the application flow.",
      manualActionType: "email_verification_code",
      jobUrl: "https://jobs.stripe.com/openings/software-engineer-new-grad",
      applyUrl: "https://jobs.stripe.com/openings/software-engineer-new-grad/apply",
      lastAutomationUrl: "https://jobs.stripe.com/openings/software-engineer-new-grad/apply",
      preparedAt: "2026-04-21T07:40:00.000Z",
      submittedAt: null,
      needsUserActionAt: "2026-04-21T07:51:00.000Z",
      updatedAt: "2026-04-21T07:51:00.000Z",
      generatedAnswersCount: 3,
    },
    {
      id: "app_4",
      company: "Notion",
      role: "Product Engineer",
      source: "Greenhouse",
      location: "New York, NY",
      fitScore: 77,
      status: "queued",
      blockingReason: null,
      manualActionType: null,
      jobUrl: "https://boards.greenhouse.io/notion/jobs/67890",
      applyUrl: "https://boards.greenhouse.io/notion/apply/67890",
      lastAutomationUrl: null,
      preparedAt: null,
      submittedAt: null,
      needsUserActionAt: null,
      updatedAt: "2026-04-21T06:20:00.000Z",
      generatedAnswersCount: 0,
    },
  ],
  notifications: [
    {
      id: "notification_1",
      type: "success",
      title: "11 applications auto-submitted today",
      message: "Simple flows were completed automatically and confirmation states were captured.",
      createdAt: "2026-04-21T09:20:00.000Z",
    },
    {
      id: "notification_2",
      type: "action_required",
      title: "Stripe needs manual completion",
      message: "A verification prompt interrupted the apply flow. Resume data is preserved for a quick handoff.",
      createdAt: "2026-04-21T07:52:00.000Z",
    },
  ],
};
